### ISSUE TITLE
Enhancement - Make systems in Timeline reflect changes in Systems

### ISSUE THREAD

**Issue by PeterWagenaarNW** [cyb3rfox/Aurora-Incident-Response#17]
Right now, when you change the hostname in the Systems overview for one of the hosts, the entries under "Event System" and "Remote System" in Timeline don't change along with it. It may be nice to have those reflect the changed hostname. Right now you have to change them all manually.

**Comment by cyb3rfox** [comment]
The systems tab is usually propagated with data from external sources. I can see that you might want to change the hostnames you added manually at the beginning of the gig. It's technically possible and I will look into it.

**Comment by cyb3rfox** [comment]
Additional note...it needs to affect all tables that have a hostname column

**Comment by cyb3rfox** [comment]
Fixed
