### ISSUE TITLE
Enhancement - Add description field to Systems

### ISSUE THREAD

**Issue by PeterWagenaarNW** [cyb3rfox/Aurora-Incident-Response#18]
It would be nice to be able to add another column to the Systems, so you can add some notes to each (like: "main DC" or "probably TOR exit node")

**Comment by cyb3rfox** [comment]
If it is an item that's interesting it needs to be in the investigated systems. After all, when you look up an IP on shodan you did investigate and you have results to note. The System table is strictly to propagate the other tables columns.

**Comment by PeterWagenaarNW** [comment]
Don't you think that, even if it's not specifically an interesting system, it would be nice to note down the function of a system or something?

**Comment by cyb3rfox** [comment]
Yes it's already fixed with issue #20 Will be in the next release.
