### ISSUE TITLE
Enhancement - Add Owner/Notes Column to Systems

### ISSUE THREAD

**Issue by co-devs** [cyb3rfox/Aurora-Incident-Response#20]
Add a column for Owner and / or a Notes column to the Systems view.  Useful for identifying different systems (srv-acme-132 is a domain controller, srv-acme-042 is an FTP server, etc) and for identifying workstation ownership (lap-acme-143 is Susan's laptop).

**Comment by cyb3rfox** [comment]
Will put that in the next release.
