### ISSUE TITLE
Enhacement - Use different colors for each type of incident shown in the Timeline

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#24]
Using different colors in the labels would ease the visualization and tracking of the events reported.

**Comment by cyb3rfox** [comment]
Just to clarify, you mean in the table rows, not only in the timeline?

**Comment by febrezo** [comment]
Sorry, had to force-push it twice to amend an issue when grabbing  events which does not involve two systems.

![Captura realizada el 2020-09-10 19 31 30](https://user-images.githubusercontent.com/1590496/92772793-541f3300-f39c-11ea-915b-9765e84bab51.png)
