### ISSUE TITLE
Enhacement - Add date information in the Lateral Movement visualization

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#25]

**Comment by cyb3rfox** [comment]
I like the idea, but there could be multiple dates. Need to figure out a way to display that conveniently.

**Comment by febrezo** [comment]
If there are several connections between different items, I guess that they should be added as different communications in the timelines view.  I'll explore the visualization library to try to draw it appropriately. I'll let you know if I find something that matches.
