### ISSUE TITLE
Enhacement - Add system type to the Systems description tab

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#26]
Both options would be interesting to provide further description on the systems. The information could then be used to colorize the Lateral Movement diagram. `Type` would refer to the type of the system, e. g., `Desktop`, `Server`, `Phone`, `IoT device`, `Other`. This could be a combobox.

**Comment by cyb3rfox** [comment]
Merged. Thanks @febrezo
