### ISSUE TITLE
Bug | Capturing lock when closing from the X

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#34]
I'm not sure yet if this is only taking place in my development scenario, but when I open a .fox file in the development version the file automatically gets locked if it was unlocked (which is expected). The problem is that if the application is closed with the X the file will remain locked the next time you open it so you cannot edit it.

Although this will probably need further discussion, it may be interesting to:

- [ ] Provide a «Lock and quit» button
- [ ] Provide a «Unlock and quit» button
- [ ] Capture the window destroy event when pressing X to ask whether you want to  unlock the file or not
- [ ] Provide a new action that will force unlock for these cases prompting the user that this may lead to inconsistencies if the file is being shared.

Otherwise, the only way I found to unlock the file is to manually edit the Json.

**Comment by cyb3rfox** [comment]
Upon quit it should release the lock. There was a race condition problem in the past but i haven0t seen that anymore, except when i force-kill the program.

**Comment by febrezo** [comment]
Let me check that in-depth to improve the description of the issue. That might be the point as I generally Ctrl+C the application during development.

**Comment by cyb3rfox** [comment]
For now I implemented a "force unlock" button into the menu. That saves you from opening the file in notepad. It's also needed as a prereq to implement encryption.
