### ISSUE TITLE
Bug | Update current screen when loading a new engagement

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#41]
At the moment, if you open a new engagement while you are in e. g., the Visual Timeline watching the current case, the load of the new file does not enforce a graph visualization. It will still show the graph from the previous case until the tab is manually clicked again.

**Comment by cyb3rfox** [comment]
Ok, I would just set the default screen to timeline when somebody opens a new file. Good catch.

**Comment by cyb3rfox** [comment]
fixes in  2749694
