### ISSUE TITLE
Bug | Updating the name of a system does not update it neither in the Timeline nor the Investigated Systems

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#42]
This will lead to inconsistencies when reporting. The update event might be needed to be grabbed somewhere to update that.

**Comment by cyb3rfox** [comment]
Duplicate of #11

**Comment by cyb3rfox** [comment]
Wrong line. it'll require some major refactoring but has to come

**Comment by cyb3rfox** [comment]
Duplicate of #17
