### ISSUE TITLE
More APIs

### ISSUE THREAD

**Issue by PeterM1981** [cyb3rfox/Aurora-Incident-Response#50]
I'm sure there are plenty of other APIs that would also be great to integrate with, so please consider the one I would like as an example. 

I would like support for the Sophos Central API (https://developer.sophos.com/) this would allow (for example) my team who are working with a customer to link our Aurora file to their management console, automatically bringing in device and user details, as well as recent and live detection events.

**Comment by cyb3rfox** [comment]
Defiitely on the roadmap. Do you have a test instance for sophos? It might be easier to implement into a new project I'm working on. let's see.

**Comment by cyb3rfox** [comment]
Closed due to inactivity.
