### ISSUE TITLE
Value added to the first column of the Systems table overwrites the values in the first column of the OSInt table.

### ISSUE THREAD

**Issue by CyberKaizen** [cyb3rfox/Aurora-Incident-Response#56]
How to reproduce the issue:
Add a value to first column of System table:
![image](https://user-images.githubusercontent.com/78124503/109231368-149ea480-778c-11eb-97ac-6ca8b81ccf5d.png)

Add value to first column of OSInt Table:
![image](https://user-images.githubusercontent.com/78124503/109231441-3b5cdb00-778c-11eb-899c-1d79f6ea8680.png)

Then save the .fox file, close Aurora then re-open Aurora and open the .fox file.

Which results in the OSInt table getting overwritten with data from the System table:
![image](https://user-images.githubusercontent.com/78124503/109231542-6b0be300-778c-11eb-8418-42f8dd863e03.png)

**Comment by cyb3rfox** [comment]
It's a bug, sorry. I'll fix that in the next release. Also see #60
