### ISSUE TITLE
Show icon legend for VT results

### ISSUE THREAD

**Issue by cyb3rfox** [cyb3rfox/Aurora-Incident-Response#6]
VT Results are not fully self-explaining. Need a legend there and maybe a details view

**Comment by co-devs** [comment]
Legend in lateral movement and visual timeline would be helpful too.  "What is the red?"

**Comment by cyb3rfox** [comment]
For these I was thinking about letting the user decide via case config. Still makes sense to add a legend.

**Comment by cyb3rfox** [comment]
Added Info Button to malware lines. This shows the vt result in text. I'll touch this again when I add detail views for every line.
