### ISSUE TITLE
Proposal: Expected working flow for OSINT tab not clear

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#60]
Currently I'm experiencing that the OSINT tab clones the values in the Systems tab. This is a bit confusing because there is no space to add multiple sources and evaluate them separately. At the same time, if you remove a row in the tab it seems to corrupt the information in the Systems table by removing details although "links" are still kept in the Timeline tab.

In a recent incident, a backup saved my life after manually removing lines in the OSINT tab but I guess that in the current design the usage is confusing.

I propose a fully redesign of this tab to include the following columns:

- Informatio date (required to keep track of evolving data)
- Asset (taken from a combobox taking information from the 'Systems' tab)
- Description (free text)
- URL (free text for the link)
- Confidence (STIX uses values from 0-100, but I feel more comfortable with a combobox including a clearer decriptive explanation using FM 2.22-3 proposal which evaluates confidence from 1 to 6 as follows):

```
1 - Confirmed. Confirmed by other independent sources; logical in itself; Consistent with other information on the subject 
2 - Probably True. Not confirmed; logical in itself; consistent with other information on the subject
3 - Possibly True. Not confirmed; reasonably logical in itself; agrees with some other information on the subject
4 - Doubtfully True. Not confirmed; possible but not logical; no other information on the subject
5 - Improbable Not confirmed; not logical in itself; contradicted by other information on the subject
6 - Cannot Be Judged No basis exists for evaluating the validity of the information
```

Feel free to add any other valuable comments. This is just an idea.

**Comment by cyb3rfox** [comment]
That's a bug. The columns were from a different issue. The idea is not to store technical int but rather links to article you come across while investigating. It's rathe runstructured storage. Real technical intel is in the other tabs or whatever intel storage you use (misp/opencti...)
