### ISSUE TITLE
Add email, phone, other and affiliation columns to the Investigators tab.

### ISSUE THREAD

**Issue by febrezo** [cyb3rfox/Aurora-Incident-Response#62]
Considering that Aurora should be a tool to keep track of each aspect of incident handling, it is a bit confusing to use contact information under the Full name tab. Adding new columns to keep track of this should not be something messy but helpful.

Proposed new columns are:

- Email contact (free text)
- Phone contact (free text)
- Other contact (free text)
- Affiliation (free text)

**Comment by cyb3rfox** [comment]
that's a very good point. will put that in the next release for sure
