### ISSUE TITLE
Evidences tab erased after closing the program

### ISSUE THREAD

**Issue by Doka7** [cyb3rfox/Aurora-Incident-Response#73]
Hello, I have recently started using Aurora IR and I find it really useful, thank you for your contribution to the community!

Maybe I did something wrong due to my inexperience using the tool, but yesterday I started with the documentation of a security incident and today when I reopened the file I found that everything was saved except from the Evidences tab, which is blank. Is this some kind of bug?

Thank you in advance.

**Comment by cyb3rfox** [comment]
Thank you for your feedback. There was an error in the loading logic. It's fixed in the code now and I will create a new release in the coming days. Sorry for the inconveniences.
