### ISSUE TITLE
Search function do not work as expected

### ISSUE THREAD

**Issue by Doka7** [cyb3rfox/Aurora-Incident-Response#81]
When I search for something I usually don't get results, it seems like is not implemented as a CONTAINS function. Could be?

**Comment by cyb3rfox** [comment]
It is, you need to go into the detailed search.

**Comment by cyb3rfox** [comment]
![image](https://user-images.githubusercontent.com/33657602/114896073-4e953a00-9e10-11eb-8985-39fc853804f4.png)
![image](https://user-images.githubusercontent.com/33657602/114896133-5a80fc00-9e10-11eb-9991-198622cfb0e5.png)

**Comment by Doka7** [comment]
Thank you so much.

**Comment by cyb3rfox** [comment]
Thank you for all the input. That helps me making it better.
