### ISSUE TITLE
Import evidence does not work (blank lines)

### ISSUE THREAD

**Issue by boingomw** [cyb3rfox/Aurora-Incident-Response#83]
I started with an export of existing data, and tried to reimport that data.  It gave me this:
<img width="411" alt="Untitled" src="https://user-images.githubusercontent.com/17418298/128204430-75ee5997-a026-41f8-aa99-1f4aa5024235.png">

If I continue the import, it ends up importing a number of blank lines equal to the lines in the file.
File content looks like this:

system0,,Desktop,,,,
system1, ,Desktop,, , ,TRUE
system2,,Desktop,,,,
system3,,Desktop,Win10,,,
system4, ,Desktop,, , ,TRUE
system5,,Desktop,,,,
system6,,Desktop,Win10,,,
system7,,Desktop,,,,
system8,,Desktop,Win7,,,
system9,127.0.0.1,Desktop,,,desc,TRUE
system10,,Desktop,Win7,,,

I then tried various changes, including file type (PC to unix and back), Ascii vs unicode, recreated file from scratch.  all fail.  Also tried with and without header line.

V 0.6.6, windows x64

**Comment by boingomw** [comment]
Nevermind.

I didn't realize I had to click on the first line in order to get a dropdown.  I expected it to be populated with my first line of text.  my bad.

**Comment by amgeryom** [comment]
Hi i'm having the same issue but when i get the drop down the only thing i see is "Empty List". is there something im doing wrong :(
